version: "1"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PGDATA: /data/postgres
    expose:
      - 5432
    networks:
      - database
    volumes:
      - postgres:/data/postgres

  pgADmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
    ports:
      - 5050:80
    networks:
      - database
    volumes:
      - pgadmin:/var/lib/pgadmin

  app:
    build:
      context: . 
      dockerfile: ./Docker/Dockerfile
    ports:
      - 80:80
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_URL: postgres
    depends_on:
      - postgres
    networks:
      - database
    command: bash -c "python ./src/app/utils.py && uvicorn src.app.main:app --host 0.0.0.0 --port 80 --reload"


networks:
  database:
    driver: bridge
    

volumes:
  postgres:
  pgadmin: